[package]
name = "ionic"
version = "0.1.0"
edition = "2024"

[dependencies]
# anyhow = "1"
# env_logger = "0.11"
log = {workspace = true}
base64 = "0.23"
rand = "0.10"
blake3 = "1.8"
blst = "0.3"
ed25519-dalek = { version = "3", features = ["rand_core"] }
ark-std = "0.6"
ark-bls12-381 = "0.6"
ark-ff = "0.6"
ark-ec = "0.6"
ark-poly = "0.6"
ark-serialize = "0.6"
