[package]
name = "iovault"
version = "0.1.0"
edition = "2024"

[dependencies]
ionic = { path = "../ionic" }
anyhow = "1"
env_logger = "0.11"
clap = { version = "4.6", features = ["derive"] }
log = {workspace = true}
rand = {workspace = true}
blake3 = {workspace = true}
blst = {workspace = true}
ed25519-dalek = {workspace = true}
