use std::fmt::Display;

use crate::vm::VMExecutionError;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IonicOpcode {
    STOP = 0x00,
    ADD = 0x01,
    MUL = 0x02,
    SUB = 0x03,
    DIV = 0x04,
    SDIV = 0x05,
    MOD = 0x06,
    SMOD = 0x07,
    ADDMOD = 0x08,
    MULMOD = 0x09,
    EXP = 0x0A,
    SIGNEXTEND = 0x0B,
    LT = 0x10,
    GT = 0x11,
    SLT = 0x12,
    SGT = 0x13,
    EQ = 0x14,
    ISZERO = 0x15,
    AND = 0x16,
    OR = 0x17,
    XOR = 0x18,
    NOT = 0x19,
    BYTE = 0x1A,
    SHL = 0x1B,
    SHR = 0x1C,
    SAR = 0x1D,
    KECCAK256 = 0x20,
    ADDRESS = 0x30,
    BALANCE = 0x31,
    ORIGIN = 0x32,
    CALLER = 0x33,
    CALLVALUE = 0x34,
    CALLDATALOAD = 0x35,
    CALLDATASIZE = 0x36,
    CALLDATACOPY = 0x37,
    CODESIZE = 0x38,
    CODECOPY = 0x39,
    GASPRICE = 0x3A,
    EXTCODESIZE = 0x3B,
    EXTCODECOPY = 0x3C,
    RETURNDATASIZE = 0x3D,
    RETURNDATACOPY = 0x3E,
    EXTCODEHASH = 0x3F,
    BLOCKHASH = 0x40,
    COINBASE = 0x41,
    TIMESTAMP = 0x42,
    NUMBER = 0x43,
    PREVRANDAO = 0x44,
    GASLIMIT = 0x45,
    CHAINID = 0x46,
    SELFBALANCE = 0x47,
    BASEFEE = 0x48,
    BLOBHASH = 0x49,
    BLOBBASEFEE = 0x4A,
    POP = 0x50,
    MLOAD = 0x51,
    MSTORE = 0x52,
    MSTORE8 = 0x53,
    SLOAD = 0x54,
    SSTORE = 0x55,
    JUMP = 0x56,
    JUMPI = 0x57,
    PC = 0x58,
    MSIZE = 0x59,
    GAS = 0x5A,
    JUMPDEST = 0x5B,
    TLOAD = 0x5C,
    TSTORE = 0x5D,
    MCOPY = 0x5E,
    PUSH0 = 0x5F,
    PUSH1 = 0x60,
    PUSH2 = 0x61,
    PUSH3 = 0x62,
    PUSH4 = 0x63,
    PUSH5 = 0x64,
    PUSH6 = 0x65,
    PUSH7 = 0x66,
    PUSH8 = 0x67,
    PUSH9 = 0x68,
    PUSH10 = 0x69,
    PUSH11 = 0x6A,
    PUSH12 = 0x6B,
    PUSH13 = 0x6C,
    PUSH14 = 0x6D,
    PUSH15 = 0x6E,
    PUSH16 = 0x6F,
    PUSH17 = 0x70,
    PUSH18 = 0x71,
    PUSH19 = 0x72,
    PUSH20 = 0x73,
    PUSH21 = 0x74,
    PUSH22 = 0x75,
    PUSH23 = 0x76,
    PUSH24 = 0x77,
    PUSH25 = 0x78,
    PUSH26 = 0x79,
    PUSH27 = 0x7A,
    PUSH28 = 0x7B,
    PUSH29 = 0x7C,
    PUSH30 = 0x7D,
    PUSH31 = 0x7E,
    PUSH32 = 0x7F,
    DUP1 = 0x80,
    DUP2 = 0x81,
    DUP3 = 0x82,
    DUP4 = 0x83,
    DUP5 = 0x84,
    DUP6 = 0x85,
    DUP7 = 0x86,
    DUP8 = 0x87,
    DUP9 = 0x88,
    DUP10 = 0x89,
    DUP11 = 0x8A,
    DUP12 = 0x8B,
    DUP13 = 0x8C,
    DUP14 = 0x8D,
    DUP15 = 0x8E,
    DUP16 = 0x8F,
    SWAP1 = 0x90,
    SWAP2 = 0x91,
    SWAP3 = 0x92,
    SWAP4 = 0x93,
    SWAP5 = 0x94,
    SWAP6 = 0x95,
    SWAP7 = 0x96,
    SWAP8 = 0x97,
    SWAP9 = 0x98,
    SWAP10 = 0x99,
    SWAP11 = 0x9A,
    SWAP12 = 0x9B,
    SWAP13 = 0x9C,
    SWAP14 = 0x9D,
    SWAP15 = 0x9E,
    SWAP16 = 0x9F,
    LOG0 = 0xA0,
    LOG1 = 0xA1,
    LOG2 = 0xA2,
    LOG3 = 0xA3,
    LOG4 = 0xA4,
    CREATE = 0xF0,
    CALL = 0xF1,
    CALLCODE = 0xF2,
    RETURN = 0xF3,
    DELEGATECALL = 0xF4,
    CREATE2 = 0xF5,
    STATICCALL = 0xFA,
    REVERT = 0xFD,
    INVALID = 0xFE,
    SELFDESTRUCT = 0xFF,
}

impl IonicOpcode {
    pub fn as_byte(&self) -> u8 {
        *self as u8
    }

    pub fn from_byte(byte: u8) -> Result<Self, VMExecutionError> {
        match byte {
            0x00 => Ok(Self::STOP),
            0x01 => Ok(Self::ADD),
            0x02 => Ok(Self::MUL),
            0x03 => Ok(Self::SUB),
            0x04 => Ok(Self::DIV),
            0x05 => Ok(Self::SDIV),
            0x06 => Ok(Self::MOD),
            0x07 => Ok(Self::SMOD),
            0x08 => Ok(Self::ADDMOD),
            0x09 => Ok(Self::MULMOD),
            0x0A => Ok(Self::EXP),
            0x0B => Ok(Self::SIGNEXTEND),
            0x10 => Ok(Self::LT),
            0x11 => Ok(Self::GT),
            0x12 => Ok(Self::SLT),
            0x13 => Ok(Self::SGT),
            0x14 => Ok(Self::EQ),
            0x15 => Ok(Self::ISZERO),
            0x16 => Ok(Self::AND),
            0x17 => Ok(Self::OR),
            0x18 => Ok(Self::XOR),
            0x19 => Ok(Self::NOT),
            0x1A => Ok(Self::BYTE),
            0x1B => Ok(Self::SHL),
            0x1C => Ok(Self::SHR),
            0x1D => Ok(Self::SAR),
            0x20 => Ok(Self::KECCAK256),
            0x30 => Ok(Self::ADDRESS),
            0x31 => Ok(Self::BALANCE),
            0x32 => Ok(Self::ORIGIN),
            0x33 => Ok(Self::CALLER),
            0x34 => Ok(Self::CALLVALUE),
            0x35 => Ok(Self::CALLDATALOAD),
            0x36 => Ok(Self::CALLDATASIZE),
            0x37 => Ok(Self::CALLDATACOPY),
            0x38 => Ok(Self::CODESIZE),
            0x39 => Ok(Self::CODECOPY),
            0x3A => Ok(Self::GASPRICE),
            0x3B => Ok(Self::EXTCODESIZE),
            0x3C => Ok(Self::EXTCODECOPY),
            0x3D => Ok(Self::RETURNDATASIZE),
            0x3E => Ok(Self::RETURNDATACOPY),
            0x3F => Ok(Self::EXTCODEHASH),
            0x40 => Ok(Self::BLOCKHASH),
            0x41 => Ok(Self::COINBASE),
            0x42 => Ok(Self::TIMESTAMP),
            0x43 => Ok(Self::NUMBER),
            0x44 => Ok(Self::PREVRANDAO),
            0x45 => Ok(Self::GASLIMIT),
            0x46 => Ok(Self::CHAINID),
            0x47 => Ok(Self::SELFBALANCE),
            0x48 => Ok(Self::BASEFEE),
            0x49 => Ok(Self::BLOBHASH),
            0x4A => Ok(Self::BLOBBASEFEE),
            0x50 => Ok(Self::POP),
            0x51 => Ok(Self::MLOAD),
            0x52 => Ok(Self::MSTORE),
            0x53 => Ok(Self::MSTORE8),
            0x54 => Ok(Self::SLOAD),
            0x55 => Ok(Self::SSTORE),
            0x56 => Ok(Self::JUMP),
            0x57 => Ok(Self::JUMPI),
            0x58 => Ok(Self::PC),
            0x59 => Ok(Self::MSIZE),
            0x5A => Ok(Self::GAS),
            0x5B => Ok(Self::JUMPDEST),
            0x5C => Ok(Self::TLOAD),
            0x5D => Ok(Self::TSTORE),
            0x5E => Ok(Self::MCOPY),
            0x5F => Ok(Self::PUSH0),
            0x60 => Ok(Self::PUSH1),
            0x61 => Ok(Self::PUSH2),
            0x62 => Ok(Self::PUSH3),
            0x63 => Ok(Self::PUSH4),
            0x64 => Ok(Self::PUSH5),
            0x65 => Ok(Self::PUSH6),
            0x66 => Ok(Self::PUSH7),
            0x67 => Ok(Self::PUSH8),
            0x68 => Ok(Self::PUSH9),
            0x69 => Ok(Self::PUSH10),
            0x6A => Ok(Self::PUSH11),
            0x6B => Ok(Self::PUSH12),
            0x6C => Ok(Self::PUSH13),
            0x6D => Ok(Self::PUSH14),
            0x6E => Ok(Self::PUSH15),
            0x6F => Ok(Self::PUSH16),
            0x70 => Ok(Self::PUSH17),
            0x71 => Ok(Self::PUSH18),
            0x72 => Ok(Self::PUSH19),
            0x73 => Ok(Self::PUSH20),
            0x74 => Ok(Self::PUSH21),
            0x75 => Ok(Self::PUSH22),
            0x76 => Ok(Self::PUSH23),
            0x77 => Ok(Self::PUSH24),
            0x78 => Ok(Self::PUSH25),
            0x79 => Ok(Self::PUSH26),
            0x7A => Ok(Self::PUSH27),
            0x7B => Ok(Self::PUSH28),
            0x7C => Ok(Self::PUSH29),
            0x7D => Ok(Self::PUSH30),
            0x7E => Ok(Self::PUSH31),
            0x7F => Ok(Self::PUSH32),
            0x80 => Ok(Self::DUP1),
            0x81 => Ok(Self::DUP2),
            0x82 => Ok(Self::DUP3),
            0x83 => Ok(Self::DUP4),
            0x84 => Ok(Self::DUP5),
            0x85 => Ok(Self::DUP6),
            0x86 => Ok(Self::DUP7),
            0x87 => Ok(Self::DUP8),
            0x88 => Ok(Self::DUP9),
            0x89 => Ok(Self::DUP10),
            0x8A => Ok(Self::DUP11),
            0x8B => Ok(Self::DUP12),
            0x8C => Ok(Self::DUP13),
            0x8D => Ok(Self::DUP14),
            0x8E => Ok(Self::DUP15),
            0x8F => Ok(Self::DUP16),
            0x90 => Ok(Self::SWAP1),
            0x91 => Ok(Self::SWAP2),
            0x92 => Ok(Self::SWAP3),
            0x93 => Ok(Self::SWAP4),
            0x94 => Ok(Self::SWAP5),
            0x95 => Ok(Self::SWAP6),
            0x96 => Ok(Self::SWAP7),
            0x97 => Ok(Self::SWAP8),
            0x98 => Ok(Self::SWAP9),
            0x99 => Ok(Self::SWAP10),
            0x9A => Ok(Self::SWAP11),
            0x9B => Ok(Self::SWAP12),
            0x9C => Ok(Self::SWAP13),
            0x9D => Ok(Self::SWAP14),
            0x9E => Ok(Self::SWAP15),
            0x9F => Ok(Self::SWAP16),
            0xA0 => Ok(Self::LOG0),
            0xA1 => Ok(Self::LOG1),
            0xA2 => Ok(Self::LOG2),
            0xA3 => Ok(Self::LOG3),
            0xA4 => Ok(Self::LOG4),
            0xF0 => Ok(Self::CREATE),
            0xF1 => Ok(Self::CALL),
            0xF2 => Ok(Self::CALLCODE),
            0xF3 => Ok(Self::RETURN),
            0xF4 => Ok(Self::DELEGATECALL),
            0xF5 => Ok(Self::CREATE2),
            0xFA => Ok(Self::STATICCALL),
            0xFD => Ok(Self::REVERT),
            0xFE => Ok(Self::INVALID),
            0xFF => Ok(Self::SELFDESTRUCT),
            _ => Err(VMExecutionError::IllegalInstruction(byte)),
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Self::STOP => "STOP",
            Self::ADD => "ADD",
            Self::MUL => "MUL",
            Self::SUB => "SUB",
            Self::DIV => "DIV",
            Self::SDIV => "SDIV",
            Self::MOD => "MOD",
            Self::SMOD => "SMOD",
            Self::ADDMOD => "ADDMOD",
            Self::MULMOD => "MULMOD",
            Self::EXP => "EXP",
            Self::SIGNEXTEND => "SIGNEXTEND",
            Self::LT => "LT",
            Self::GT => "GT",
            Self::SLT => "SLT",
            Self::SGT => "SGT",
            Self::EQ => "EQ",
            Self::ISZERO => "ISZERO",
            Self::AND => "AND",
            Self::OR => "OR",
            Self::XOR => "XOR",
            Self::NOT => "NOT",
            Self::BYTE => "BYTE",
            Self::SHL => "SHL",
            Self::SHR => "SHR",
            Self::SAR => "SAR",
            Self::KECCAK256 => "KECCAK256",
            Self::ADDRESS => "ADDRESS",
            Self::BALANCE => "BALANCE",
            Self::ORIGIN => "ORIGIN",
            Self::CALLER => "CALLER",
            Self::CALLVALUE => "CALLVALUE",
            Self::CALLDATALOAD => "CALLDATALOAD",
            Self::CALLDATASIZE => "CALLDATASIZE",
            Self::CALLDATACOPY => "CALLDATACOPY",
            Self::CODESIZE => "CODESIZE",
            Self::CODECOPY => "CODECOPY",
            Self::GASPRICE => "GASPRICE",
            Self::EXTCODESIZE => "EXTCODESIZE",
            Self::EXTCODECOPY => "EXTCODECOPY",
            Self::RETURNDATASIZE => "RETURNDATASIZE",
            Self::RETURNDATACOPY => "RETURNDATACOPY",
            Self::EXTCODEHASH => "EXTCODEHASH",
            Self::BLOCKHASH => "BLOCKHASH",
            Self::COINBASE => "COINBASE",
            Self::TIMESTAMP => "TIMESTAMP",
            Self::NUMBER => "NUMBER",
            Self::PREVRANDAO => "PREVRANDAO",
            Self::GASLIMIT => "GASLIMIT",
            Self::CHAINID => "CHAINID",
            Self::SELFBALANCE => "SELFBALANCE",
            Self::BASEFEE => "BASEFEE",
            Self::BLOBHASH => "BLOBHASH",
            Self::BLOBBASEFEE => "BLOBBASEFEE",
            Self::POP => "POP",
            Self::MLOAD => "MLOAD",
            Self::MSTORE => "MSTORE",
            Self::MSTORE8 => "MSTORE8",
            Self::SLOAD => "SLOAD",
            Self::SSTORE => "SSTORE",
            Self::JUMP => "JUMP",
            Self::JUMPI => "JUMPI",
            Self::PC => "PC",
            Self::MSIZE => "MSIZE",
            Self::GAS => "GAS",
            Self::JUMPDEST => "JUMPDEST",
            Self::TLOAD => "TLOAD",
            Self::TSTORE => "TSTORE",
            Self::MCOPY => "MCOPY",
            Self::PUSH0 => "PUSH0",
            Self::PUSH1 => "PUSH1",
            Self::PUSH2 => "PUSH2",
            Self::PUSH3 => "PUSH3",
            Self::PUSH4 => "PUSH4",
            Self::PUSH5 => "PUSH5",
            Self::PUSH6 => "PUSH6",
            Self::PUSH7 => "PUSH7",
            Self::PUSH8 => "PUSH8",
            Self::PUSH9 => "PUSH9",
            Self::PUSH10 => "PUSH10",
            Self::PUSH11 => "PUSH11",
            Self::PUSH12 => "PUSH12",
            Self::PUSH13 => "PUSH13",
            Self::PUSH14 => "PUSH14",
            Self::PUSH15 => "PUSH15",
            Self::PUSH16 => "PUSH16",
            Self::PUSH17 => "PUSH17",
            Self::PUSH18 => "PUSH18",
            Self::PUSH19 => "PUSH19",
            Self::PUSH20 => "PUSH20",
            Self::PUSH21 => "PUSH21",
            Self::PUSH22 => "PUSH22",
            Self::PUSH23 => "PUSH23",
            Self::PUSH24 => "PUSH24",
            Self::PUSH25 => "PUSH25",
            Self::PUSH26 => "PUSH26",
            Self::PUSH27 => "PUSH27",
            Self::PUSH28 => "PUSH28",
            Self::PUSH29 => "PUSH29",
            Self::PUSH30 => "PUSH30",
            Self::PUSH31 => "PUSH31",
            Self::PUSH32 => "PUSH32",
            Self::DUP1 => "DUP1",
            Self::DUP2 => "DUP2",
            Self::DUP3 => "DUP3",
            Self::DUP4 => "DUP4",
            Self::DUP5 => "DUP5",
            Self::DUP6 => "DUP6",
            Self::DUP7 => "DUP7",
            Self::DUP8 => "DUP8",
            Self::DUP9 => "DUP9",
            Self::DUP10 => "DUP10",
            Self::DUP11 => "DUP11",
            Self::DUP12 => "DUP12",
            Self::DUP13 => "DUP13",
            Self::DUP14 => "DUP14",
            Self::DUP15 => "DUP15",
            Self::DUP16 => "DUP16",
            Self::SWAP1 => "SWAP1",
            Self::SWAP2 => "SWAP2",
            Self::SWAP3 => "SWAP3",
            Self::SWAP4 => "SWAP4",
            Self::SWAP5 => "SWAP5",
            Self::SWAP6 => "SWAP6",
            Self::SWAP7 => "SWAP7",
            Self::SWAP8 => "SWAP8",
            Self::SWAP9 => "SWAP9",
            Self::SWAP10 => "SWAP10",
            Self::SWAP11 => "SWAP11",
            Self::SWAP12 => "SWAP12",
            Self::SWAP13 => "SWAP13",
            Self::SWAP14 => "SWAP14",
            Self::SWAP15 => "SWAP15",
            Self::SWAP16 => "SWAP16",
            Self::LOG0 => "LOG0",
            Self::LOG1 => "LOG1",
            Self::LOG2 => "LOG2",
            Self::LOG3 => "LOG3",
            Self::LOG4 => "LOG4",
            Self::CREATE => "CREATE",
            Self::CALL => "CALL",
            Self::CALLCODE => "CALLCODE",
            Self::RETURN => "RETURN",
            Self::DELEGATECALL => "DELEGATECALL",
            Self::CREATE2 => "CREATE2",
            Self::STATICCALL => "STATICCALL",
            Self::REVERT => "REVERT",
            Self::INVALID => "INVALID",
            Self::SELFDESTRUCT => "SELFDESTRUCT",
        }
    }

    pub fn is_push(self) -> bool {
        matches!(self, Self::PUSH0 | Self::PUSH1 | Self::PUSH2 | Self::PUSH3 |
            Self::PUSH4 | Self::PUSH5 | Self::PUSH6 | Self::PUSH7 |
            Self::PUSH8 | Self::PUSH9 | Self::PUSH10 | Self::PUSH11 |
            Self::PUSH12 | Self::PUSH13 | Self::PUSH14 | Self::PUSH15 |
            Self::PUSH16 | Self::PUSH17 | Self::PUSH18 | Self::PUSH19 |
            Self::PUSH20 | Self::PUSH21 | Self::PUSH22 | Self::PUSH23 |
            Self::PUSH24 | Self::PUSH25 | Self::PUSH26 | Self::PUSH27 |
            Self::PUSH28 | Self::PUSH29 | Self::PUSH30 | Self::PUSH31 |
            Self::PUSH32)
    }

    pub fn push_size(self) -> Option<u8> {
        match self {
            Self::PUSH0 => Some(0),
            Self::PUSH1 => Some(1),
            Self::PUSH2 => Some(2),
            Self::PUSH3 => Some(3),
            Self::PUSH4 => Some(4),
            Self::PUSH5 => Some(5),
            Self::PUSH6 => Some(6),
            Self::PUSH7 => Some(7),
            Self::PUSH8 => Some(8),
            Self::PUSH9 => Some(9),
            Self::PUSH10 => Some(10),
            Self::PUSH11 => Some(11),
            Self::PUSH12 => Some(12),
            Self::PUSH13 => Some(13),
            Self::PUSH14 => Some(14),
            Self::PUSH15 => Some(15),
            Self::PUSH16 => Some(16),
            Self::PUSH17 => Some(17),
            Self::PUSH18 => Some(18),
            Self::PUSH19 => Some(19),
            Self::PUSH20 => Some(20),
            Self::PUSH21 => Some(21),
            Self::PUSH22 => Some(22),
            Self::PUSH23 => Some(23),
            Self::PUSH24 => Some(24),
            Self::PUSH25 => Some(25),
            Self::PUSH26 => Some(26),
            Self::PUSH27 => Some(27),
            Self::PUSH28 => Some(28),
            Self::PUSH29 => Some(29),
            Self::PUSH30 => Some(30),
            Self::PUSH31 => Some(31),
            Self::PUSH32 => Some(32),
            _ => None,
        }
    }

    pub fn is_dup(self) -> bool {
        matches!(self,
            Self::DUP1 | Self::DUP2 | Self::DUP3 | Self::DUP4 |
            Self::DUP5 | Self::DUP6 | Self::DUP7 | Self::DUP8 |
            Self::DUP9 | Self::DUP10 | Self::DUP11 | Self::DUP12 |
            Self::DUP13 | Self::DUP14 | Self::DUP15 | Self::DUP16)
    }

    pub fn stack_position(self) -> Option<u8> {
        match self {
            Self::DUP1 | Self::SWAP1 => Some(1),
            Self::DUP2 | Self::SWAP2 => Some(2),
            Self::DUP3 | Self::SWAP3 => Some(3),
            Self::DUP4 | Self::SWAP4 => Some(4),
            Self::DUP5 | Self::SWAP5 => Some(5),
            Self::DUP6 | Self::SWAP6 => Some(6),
            Self::DUP7 | Self::SWAP7 => Some(7),
            Self::DUP8 | Self::SWAP8 => Some(8),
            Self::DUP9 | Self::SWAP9 => Some(9),
            Self::DUP10 | Self::SWAP10 => Some(10),
            Self::DUP11 | Self::SWAP11 => Some(11),
            Self::DUP12 | Self::SWAP12 => Some(12),
            Self::DUP13 | Self::SWAP13 => Some(13),
            Self::DUP14 | Self::SWAP14 => Some(14),
            Self::DUP15 | Self::SWAP15 => Some(15),
            Self::DUP16 | Self::SWAP16 => Some(16),
            _ => None,
        }
    }

    pub fn is_swap(self) -> bool {
        matches!(self,
            Self::SWAP1 | Self::SWAP2 | Self::SWAP3 | Self::SWAP4 |
            Self::SWAP5 | Self::SWAP6 | Self::SWAP7 | Self::SWAP8 |
            Self::SWAP9 | Self::SWAP10 | Self::SWAP11 | Self::SWAP12 |
            Self::SWAP13 | Self::SWAP14 | Self::SWAP15 | Self::SWAP16)
    }

    pub fn is_log(self) -> bool {
        matches!(self, Self::LOG0 | Self::LOG1 | Self::LOG2 | Self::LOG3 | Self::LOG4)
    }

    pub fn log_topics(self) -> Option<u8> {
        match self {
            Self::LOG0 => Some(0),
            Self::LOG1 => Some(1),
            Self::LOG2 => Some(2),
            Self::LOG3 => Some(3),
            Self::LOG4 => Some(4),
            _ => None,
        }
    }

    pub fn gas(self) -> Option<u64> {
        match self {
            Self::STOP => Some(0),
            Self::ADD => Some(3),
            Self::MUL => Some(5),
            Self::SUB => Some(3),
            Self::DIV => Some(5),
            Self::SDIV => Some(5),
            Self::MOD => Some(5),
            Self::SMOD => Some(5),
            Self::ADDMOD => Some(8),
            Self::MULMOD => Some(8),
            Self::EXP => None,
            Self::SIGNEXTEND => Some(5),
            Self::LT => Some(3),
            Self::GT => Some(3),
            Self::SLT => Some(3),
            Self::SGT => Some(3),
            Self::EQ => Some(3),
            Self::ISZERO => Some(3),
            Self::AND => Some(3),
            Self::OR => Some(3),
            Self::XOR => Some(3),
            Self::NOT => Some(3),
            Self::BYTE => Some(3),
            Self::SHL => Some(3),
            Self::SHR => Some(3),
            Self::SAR => Some(3),
            Self::KECCAK256 => None,
            Self::ADDRESS => Some(2),
            Self::BALANCE => None,
            Self::ORIGIN => Some(2),
            Self::CALLER => Some(2),
            Self::CALLVALUE => Some(2),
            Self::CALLDATALOAD => Some(3),
            Self::CALLDATASIZE => Some(2),
            Self::CALLDATACOPY => None,
            Self::CODESIZE => Some(2),
            Self::CODECOPY => None,
            Self::GASPRICE => Some(2),
            Self::EXTCODESIZE => None,
            Self::EXTCODECOPY => None,
            Self::RETURNDATASIZE => Some(2),
            Self::RETURNDATACOPY => None,
            Self::EXTCODEHASH => None,
            Self::BLOCKHASH => Some(20),
            Self::COINBASE => Some(2),
            Self::TIMESTAMP => Some(2),
            Self::NUMBER => Some(2),
            Self::PREVRANDAO => Some(2),
            Self::GASLIMIT => Some(2),
            Self::CHAINID => Some(2),
            Self::SELFBALANCE => Some(5),
            Self::BASEFEE => Some(2),
            Self::BLOBHASH => Some(3),
            Self::BLOBBASEFEE => Some(2),
            Self::POP => Some(2),
            Self::MLOAD => Some(3),
            Self::MSTORE => Some(3),
            Self::MSTORE8 => Some(3),
            Self::SLOAD => None,
            Self::SSTORE => None,
            Self::JUMP => Some(8),
            Self::JUMPI => Some(10),
            Self::PC => Some(2),
            Self::MSIZE => Some(2),
            Self::GAS => Some(2),
            Self::JUMPDEST => Some(1),
            Self::TLOAD => Some(100),
            Self::TSTORE => Some(100),
            Self::MCOPY => None,
            Self::PUSH0 => Some(2),
            Self::PUSH1 => Some(3),
            Self::PUSH2 => Some(3),
            Self::PUSH3 => Some(3),
            Self::PUSH4 => Some(3),
            Self::PUSH5 => Some(3),
            Self::PUSH6 => Some(3),
            Self::PUSH7 => Some(3),
            Self::PUSH8 => Some(3),
            Self::PUSH9 => Some(3),
            Self::PUSH10 => Some(3),
            Self::PUSH11 => Some(3),
            Self::PUSH12 => Some(3),
            Self::PUSH13 => Some(3),
            Self::PUSH14 => Some(3),
            Self::PUSH15 => Some(3),
            Self::PUSH16 => Some(3),
            Self::PUSH17 => Some(3),
            Self::PUSH18 => Some(3),
            Self::PUSH19 => Some(3),
            Self::PUSH20 => Some(3),
            Self::PUSH21 => Some(3),
            Self::PUSH22 => Some(3),
            Self::PUSH23 => Some(3),
            Self::PUSH24 => Some(3),
            Self::PUSH25 => Some(3),
            Self::PUSH26 => Some(3),
            Self::PUSH27 => Some(3),
            Self::PUSH28 => Some(3),
            Self::PUSH29 => Some(3),
            Self::PUSH30 => Some(3),
            Self::PUSH31 => Some(3),
            Self::PUSH32 => Some(3),
            Self::DUP1 => Some(3),
            Self::DUP2 => Some(3),
            Self::DUP3 => Some(3),
            Self::DUP4 => Some(3),
            Self::DUP5 => Some(3),
            Self::DUP6 => Some(3),
            Self::DUP7 => Some(3),
            Self::DUP8 => Some(3),
            Self::DUP9 => Some(3),
            Self::DUP10 => Some(3),
            Self::DUP11 => Some(3),
            Self::DUP12 => Some(3),
            Self::DUP13 => Some(3),
            Self::DUP14 => Some(3),
            Self::DUP15 => Some(3),
            Self::DUP16 => Some(3),
            Self::SWAP1 => Some(3),
            Self::SWAP2 => Some(3),
            Self::SWAP3 => Some(3),
            Self::SWAP4 => Some(3),
            Self::SWAP5 => Some(3),
            Self::SWAP6 => Some(3),
            Self::SWAP7 => Some(3),
            Self::SWAP8 => Some(3),
            Self::SWAP9 => Some(3),
            Self::SWAP10 => Some(3),
            Self::SWAP11 => Some(3),
            Self::SWAP12 => Some(3),
            Self::SWAP13 => Some(3),
            Self::SWAP14 => Some(3),
            Self::SWAP15 => Some(3),
            Self::SWAP16 => Some(3),
            Self::LOG0 => None,
            Self::LOG1 => None,
            Self::LOG2 => None,
            Self::LOG3 => None,
            Self::LOG4 => None,
            Self::CREATE => None,
            Self::CALL => None,
            Self::CALLCODE => None,
            Self::RETURN => Some(0),
            Self::DELEGATECALL => None,
            Self::CREATE2 => None,
            Self::STATICCALL => None,
            Self::REVERT => Some(0),
            Self::INVALID => None,
            Self::SELFDESTRUCT => None,
        }
    }

    pub fn has_immediate(self) -> bool {
        matches!(self,
            Self::PUSH1  | Self::PUSH2  | Self::PUSH3  | Self::PUSH4  |
            Self::PUSH5  | Self::PUSH6  | Self::PUSH7  | Self::PUSH8  |
            Self::PUSH9  | Self::PUSH10 | Self::PUSH11 | Self::PUSH12 |
            Self::PUSH13 | Self::PUSH14 | Self::PUSH15 | Self::PUSH16 |
            Self::PUSH17 | Self::PUSH18 | Self::PUSH19 | Self::PUSH20 |
            Self::PUSH21 | Self::PUSH22 | Self::PUSH23 | Self::PUSH24 |
            Self::PUSH25 | Self::PUSH26 | Self::PUSH27 | Self::PUSH28 |
            Self::PUSH29 | Self::PUSH30 | Self::PUSH31 | Self::PUSH32
        )
    }

    pub fn pops(self) -> u8 {
        match self {
            Self::STOP => 0,
            Self::ADD => 2,
            Self::MUL => 2,
            Self::SUB => 2,
            Self::DIV => 2,
            Self::SDIV => 2,
            Self::MOD => 2,
            Self::SMOD => 2,
            Self::ADDMOD => 3,
            Self::MULMOD => 3,
            Self::EXP => 2,
            Self::SIGNEXTEND => 2,
            Self::LT => 2,
            Self::GT => 2,
            Self::SLT => 2,
            Self::SGT => 2,
            Self::EQ => 2,
            Self::ISZERO => 1,
            Self::AND => 2,
            Self::OR => 2,
            Self::XOR => 2,
            Self::NOT => 1,
            Self::BYTE => 2,
            Self::SHL => 2,
            Self::SHR => 2,
            Self::SAR => 2,
            Self::KECCAK256 => 2,
            Self::ADDRESS => 0,
            Self::BALANCE => 1,
            Self::ORIGIN => 0,
            Self::CALLER => 0,
            Self::CALLVALUE => 0,
            Self::CALLDATALOAD => 1,
            Self::CALLDATASIZE => 0,
            Self::CALLDATACOPY => 3,
            Self::CODESIZE => 0,
            Self::CODECOPY => 3,
            Self::GASPRICE => 0,
            Self::EXTCODESIZE => 1,
            Self::EXTCODECOPY => 4,
            Self::RETURNDATASIZE => 0,
            Self::RETURNDATACOPY => 3,
            Self::EXTCODEHASH => 1,
            Self::BLOCKHASH => 1,
            Self::COINBASE => 0,
            Self::TIMESTAMP => 0,
            Self::NUMBER => 0,
            Self::PREVRANDAO => 0,
            Self::GASLIMIT => 0,
            Self::CHAINID => 0,
            Self::SELFBALANCE => 0,
            Self::BASEFEE => 0,
            Self::BLOBHASH => 1,
            Self::BLOBBASEFEE => 0,
            Self::POP => 1,
            Self::MLOAD => 1,
            Self::MSTORE => 2,
            Self::MSTORE8 => 2,
            Self::SLOAD => 1,
            Self::SSTORE => 2,
            Self::JUMP => 1,
            Self::JUMPI => 2,
            Self::PC => 0,
            Self::MSIZE => 0,
            Self::GAS => 0,
            Self::JUMPDEST => 0,
            Self::TLOAD => 1,
            Self::TSTORE => 2,
            Self::MCOPY => 3,
            Self::PUSH0 => 0,
            Self::PUSH1 => 0,
            Self::PUSH2 => 0,
            Self::PUSH3 => 0,
            Self::PUSH4 => 0,
            Self::PUSH5 => 0,
            Self::PUSH6 => 0,
            Self::PUSH7 => 0,
            Self::PUSH8 => 0,
            Self::PUSH9 => 0,
            Self::PUSH10 => 0,
            Self::PUSH11 => 0,
            Self::PUSH12 => 0,
            Self::PUSH13 => 0,
            Self::PUSH14 => 0,
            Self::PUSH15 => 0,
            Self::PUSH16 => 0,
            Self::PUSH17 => 0,
            Self::PUSH18 => 0,
            Self::PUSH19 => 0,
            Self::PUSH20 => 0,
            Self::PUSH21 => 0,
            Self::PUSH22 => 0,
            Self::PUSH23 => 0,
            Self::PUSH24 => 0,
            Self::PUSH25 => 0,
            Self::PUSH26 => 0,
            Self::PUSH27 => 0,
            Self::PUSH28 => 0,
            Self::PUSH29 => 0,
            Self::PUSH30 => 0,
            Self::PUSH31 => 0,
            Self::PUSH32 => 0,
            Self::DUP1 => 1,
            Self::DUP2 => 2,
            Self::DUP3 => 3,
            Self::DUP4 => 4,
            Self::DUP5 => 5,
            Self::DUP6 => 6,
            Self::DUP7 => 7,
            Self::DUP8 => 8,
            Self::DUP9 => 9,
            Self::DUP10 => 10,
            Self::DUP11 => 11,
            Self::DUP12 => 12,
            Self::DUP13 => 13,
            Self::DUP14 => 14,
            Self::DUP15 => 15,
            Self::DUP16 => 16,
            Self::SWAP1 => 2,
            Self::SWAP2 => 3,
            Self::SWAP3 => 4,
            Self::SWAP4 => 5,
            Self::SWAP5 => 6,
            Self::SWAP6 => 7,
            Self::SWAP7 => 8,
            Self::SWAP8 => 9,
            Self::SWAP9 => 10,
            Self::SWAP10 => 11,
            Self::SWAP11 => 12,
            Self::SWAP12 => 13,
            Self::SWAP13 => 14,
            Self::SWAP14 => 15,
            Self::SWAP15 => 16,
            Self::SWAP16 => 17,
            Self::LOG0 => 2,
            Self::LOG1 => 3,
            Self::LOG2 => 4,
            Self::LOG3 => 5,
            Self::LOG4 => 6,
            Self::CREATE => 3,
            Self::CALL => 7,
            Self::CALLCODE => 7,
            Self::RETURN => 2,
            Self::DELEGATECALL => 6,
            Self::CREATE2 => 4,
            Self::STATICCALL => 6,
            Self::REVERT => 2,
            Self::INVALID => 0,
            Self::SELFDESTRUCT => 1,
        }
    }

    pub fn immediate_size(self) -> usize {
        match self {
            Self::PUSH1  => 1,
            Self::PUSH2  => 2,
            Self::PUSH3  => 3,
            Self::PUSH4  => 4,
            Self::PUSH5  => 5,
            Self::PUSH6  => 6,
            Self::PUSH7  => 7,
            Self::PUSH8  => 8,
            Self::PUSH9  => 9,
            Self::PUSH10 => 10,
            Self::PUSH11 => 11,
            Self::PUSH12 => 12,
            Self::PUSH13 => 13,
            Self::PUSH14 => 14,
            Self::PUSH15 => 15,
            Self::PUSH16 => 16,
            Self::PUSH17 => 17,
            Self::PUSH18 => 18,
            Self::PUSH19 => 19,
            Self::PUSH20 => 20,
            Self::PUSH21 => 21,
            Self::PUSH22 => 22,
            Self::PUSH23 => 23,
            Self::PUSH24 => 24,
            Self::PUSH25 => 25,
            Self::PUSH26 => 26,
            Self::PUSH27 => 27,
            Self::PUSH28 => 28,
            Self::PUSH29 => 29,
            Self::PUSH30 => 30,
            Self::PUSH31 => 31,
            Self::PUSH32 => 32,
            _ => 0,
        }
    }
}

impl Display for IonicOpcode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}

impl TryFrom<u8> for IonicOpcode {
    type Error = VMExecutionError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        IonicOpcode::from_byte(value)
    }
}

impl From<IonicOpcode> for u8 {
    fn from(op: IonicOpcode) -> u8 {
        op.as_byte()
    }
}

